# 服务
server:
  port: 8080

# MySQL
Spring:
  application:
    name: clubv2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库密码
    minIdle: 10 # 最小空闲连接数
    maxActive: 20 # 最大连接数
    maxWait: 60000 # 超时时间
    maxPoolPreparedStatementPerConnectionSize: 20 # 预编译语句最大数量

logging:
  level:
    root: info